# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.*'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build HttpClientDecorator.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish HttpClientDecorator.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp
